[package]
name = "file_encrypt"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
argon2 = "0.5.3"
clap = "4.5.20"
crypto = "0.5.1"
hex = "0.4.3"
pico-args = "0.5.0"
rand = "0.8.5"
sysinfo = "0.32.0"
